stages:
  - build
  - test
  - analyze
  - package
  - deploy

variables:
  maven_packages_cache: ".m2/repository"
  MAVEN_OPTS: "-Dmaven.repo.local=./$maven_packages_cache"

image: maven:3.8.5-openjdk-17

build:
  stage: build
  tags:
    - docker
  script:
    - mvn compile
  artifacts:
    name: $CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    paths:
      - "target/*"
    expire_in: 1 week
  cache:
    paths:
      - $maven_packages_cache

test:
  stage: test
  tags:
    - docker
  dependencies:
    - build
  script:
    - mvn test
  artifacts:
    paths:
      - "target/surefire-reports/*"
      - "target/site/jacoco/*"
    expire_in: 1 week
  cache:
    paths:
      - $maven_packages_cache

analyze:
  stage: analyze
  tags:
    - docker
  dependencies:
    - build
    - test
  script:
    - mvn sonar:sonar -Dsonar.projectKey=game2048 -Dsonar.host.url=http://sonarqube:9000 -Dsonar.login=$sonar_login -Dsonar.qualitygate.wait=true
  cache:
    paths:
      - $maven_packages_cache
  allow_failure: true

package:
  stage: package
  tags:
    - docker
  dependencies:
    - build
  script:
    - mvn package
  artifacts:
    paths:
      - "target/*.war"
    expire_in: 1 week
  cache:
    paths:
      - $maven_packages_cache

deploy_deploy:
  stage: deploy
  when: manual
  tags:
    - shell
  dependencies:
    - package
  script:
    - docker rm --force tomcat
    - docker image rm --force game2048
    - echo -e 'FROM tomcat:9-jdk17-openjdk-slim \n COPY ./target/game2048.war /usr/local/tomcat/webapps' | docker build -t game2048 -f- .
    - docker run --rm -d --name tomcat -p 8080:8080 game2048
  environment:
    name: test
    action: start
    url: http://localhost:8080/game2048
    on_stop: deploy_stop

deploy_stop:
  stage: deploy
  when: manual
  tags:
    - shell
  script:
    - docker rm --force tomcat
    - docker image rm --force game2048
  environment:
    name: test
    action: stop
