name: CI/CD

on:
  push:
    branches:
      - main
env:
  maven_packages_cache: ".m2/repository"
  MAVEN_OPTS: "-Dmaven.repo.local=./$maven_packages_cache"

jobs:
  do_everything:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java Version 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Build
        run: mvn compile

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-artifacts
          path: target/*

      - name: Test
        run: mvn test

      - name: Package
        run: mvn package

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-artifacts
          path: target/*.war

      - name: Deploy game2048
        run: |
          ls -a
          cp ./target/game2048.war /usr/local/tomcat/webapps/game2048.war

##  deploy_stop:
##    runs-on: self-hosted
##    needs: package
##    if: github.event_name == 'workflow_dispatch'
##    steps:
##      - name: Checkout code
##        uses: actions/checkout@v3
##
##      - name: Stop Tomcat
##        run: |
##          docker rm --force tomcat
##          docker image rm --force game2048
##    env:
##        url: http://localhost:8080/game2048
##    outputs:
##        url: ${{ env.url }}
